### ISSUE TITLE
Search breaks with new AND/OR logic

### ISSUE THREAD

**Issue by azerbini** [azerbini/eamena_v3#49] opened 2017-10-17 11:04 UTC
When doing any kind of search (e.g. the below), the search string breaks (ValueError 'No JSON object could be decoded)
![screen shot 2017-10-17 at 12 04 29](https://user-images.githubusercontent.com/19243127/31661650-61ddf988-b333-11e7-88ef-99890fec5baa.png)

`/search/resources?page=1&termFilter=%5B%5B%7B%22inverted%22%3Afalse%2C%22type%22%3A%22concept%22%2C%22context%22%3A%2275997a72-c5f5-48a8-a88f-3ba7a28e083d%22%2C%22context_label%22%3A%22Modern%20Country%20Territory%22%2C%22id%22%3A%22Lebanon75997a72-c5f5-48a8-a88f-3ba7a28e083d%22%2C%22text%22%3A%22Lebanon%22%2C%22value%22%3A%227935b516-63f6-47d5-9324-18c6310e9725%22%7D%5D%5D&temporalFilter=%5B%7B%22year_min_max%22%3A%5B%5D%2C%22filters%22%3A%5B%5D%2C%22inverted%22%3Afalse%7D%5D&spatialFilter=%7B%22geometry%22%3A%7B%22type%22%3A%22%22%2C%22coordinates%22%3A%5B%5D%7D%2C%22buffer%22%3A%7B%22width%22%3A%220%22%2C%22unit%22%3A%22m%22%7D%2C%22inverted%22%3Afalse%7D&mapExpanded=false&timeExpanded=false&booleanSearch=and&termFilterAndOr=%5B%22and%22%5D&termFilterGroup=%5B%22No%20group%22%5D&advancedSearch=false&include_ids=true`

**Comment by ahaith** [comment] 2017-10-17 11:07
Which branch are you testing on? The latest fixes are on ox-it/advanced-group-search-fix-master

**Comment by azerbini** [comment] 2017-10-17 11:09
@ahaith , I merged everything onto advanced-search and resolved the conflicts (I do not have a branch called advanced-group-search-fix-master) with package.css and search.js

**Comment by markdoub** [comment] 2017-10-17 12:04
Hi Andrea,

I compared the  ENV/lib/python2.7/site-packages/arches/app/media/js/search.js  file of the advanced-search branch with the http://163.1.117.168/media/js/search.js file. They should be the same but they are not.
e.g.
at  ENV/lib/python2.7/site-packages/arches/app/media/js/search.js line 793:
$(".search-box-container[data-index='0'] .toggle-combine-prev").hide();
It’s not there on the test site. (this hides the left and/or toggle)

Can the test server serve a cached version of js?

Also I noticed there is duplicated code in ENV/lib/python2.7/site-packages/arches/app/media/js/search.js:
line 469-501 looks exactly the same as 502-534 (this was maybe caused by the merge conflict)

Cheers,
Markos


On 17 Oct 2017, at 12:09, Andrea Zerbini <notifications@github.com<mailto:notifications@github.com>> wrote:


@ahaith<https://github.com/ahaith> , I merged everything onto advanced-search and resolved the conflicts (I do not have a branch called advanced-group-search-fix-master) with package.css and search.js

**Comment by azerbini** [comment] 2017-10-17 12:23
@markdoub and @ahaith Yep, my mistake. I had put an earlier version of search.js in the EAMENA app media folder. Now testing again...

**Comment by azerbini** [comment] 2017-10-17 12:24
@markdoub I have removed that chunk of duplicated code, too.

**Closed** 2017-10-17 12:38 UTC
Labels: bug
